version: '3.9'
services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: N7f68a&e69E+
      MYSQL_DATABASE: recettes
      MYSQL_USER: user
      MYSQL_PASSWORD: N7f68a&e69E+
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php80
    depends_on:
      - db
    image: php:8.0-apache
    volumes:
      - ./php:/var/www/html/
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: N7f68a&e69E+
    ports:
      - 8080:80
    depends_on:
      - db
volumes:
  db_data: