version: '3.9'
services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: N7f68a&e69E+
      MYSQL_DATABASE: recettes
      MYSQL_USER: user
      MYSQL_PASSWORD: N7f68a&e69E+
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: recettes
      MYSQL_USER: user
      MYSQL_PASSWORD: N7f68a&e69E+
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
volumes:
  db_data: